services:
  back_end:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Chat_Similar
    ports:
      - "8009:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./vector_database:/app/vector_database  # Mount the local vector database folder
      - ./main.py:/app/main.py
    restart: unless-stopped